### ISSUE TITLE
No "Select Remote Device"!

### ISSUE THREAD

**Issue by vporton** [dfinity/internet-identity#1586]
Your site says:
> Click Add new device
> Select Remote Device

There is no "Add new device" at identity.ic0.app! "Add new passkey" and "Recovery device" also don't offer to add remote device. Chromium browser.
![Screenshot from 2023-05-12 06-57-15](https://github.com/dfinity/internet-identity/assets/2900574/4ee50bb4-362e-44b0-946d-f5e533ba3068)
![Screenshot from 2023-05-12 06-58-30](https://github.com/dfinity/internet-identity/assets/2900574/cbea026e-6f04-48e1-b575-add0cb16d5cd)

**Comment by nmattia** [comment]
Hi, thanks for the report! The support team is looking into this.

> Your site says:

Can you clarify which site? Is that internetcomputer.org?

**Comment by vporton** [comment]
The site nfid.one

Apparently, I messed: I thought I will "connect" NFID to my existing Internet Computer identity.

But instead, I after some trying successfully created a new NFID identity with another identity than my previous identity.

So, that's apparently my failure.

However, you should be more clear in your on-screen messages, for users not to do the same error that I did.
