### ISSUE TITLE
Ask mobile users if they want to use a security key

### ISSUE THREAD

**Issue by krpeacock** [dfinity/internet-identity#218]
Otherwise, give them the nicer config to prefer the lock screen strategy

**Comment by nmattia** [comment]
Hi @krpeacock, is this still relevant? If so, can you clarify what you mean? Right now (after creating an anchor) we incite the user to add a seed phrase or a backup key.

**Comment by krpeacock** [comment]
This predated the initial UX decisions of Internet Identity, and isn't relevant at this point
