### ISSUE TITLE
Failures when using password manager Bitwarden to to store passkeys

### ISSUE THREAD

**Issue by bwbug** [dfinity/internet-identity#2235]
The password manager Bitwarden has the ability to store and authenticate using FIDO2-compliant passkeys.  However, when creating a passkey to register an identity on `identity.internetcomputer.org`, after the passkey is stored in Bitwarden, the website returns the following error message (as reported [here](https://community.bitwarden.com/t/unable-to-create-passkeys/62644)):

`Failed to create identity: An error occurred during construction: Error: Could not create credentials.`

Moreover, if an identity has been registered by storing the passkey on a Yubikey, then attempting to create a "Recovery Device" and storing the recovery passkey in Bitwarden fails silently (the passkey is created and stored in Bitwarden, but does not register as a "Recovery Device" on identity.internetcomputer.org).

Furthermore, if an identity has been registered by storing the passkey on a Yubikey, then attempting to use <kbd>Add new passkey</kbd> fails with the following error message after the FIDO2 passkey is stored in Bitwarden:

```
Failed to add new device
We failed to add the new device to this Identity Anchor. Please try again.
Error details:
Could not create credentials.
```

**Comment by nmattia** [comment]
Hi, thanks for the report! I'll look into this ASAP.

**Comment by mzurs** [comment]
Any updates?

**Comment by nmattia** [comment]
Haven't gotten to this. I'll give an update here as soon as I get started!

**Comment by rsutton1** [comment]
Any updates? This issue is preventing me from using dapps :( I want to try it out!

**Comment by trmaphi** [comment]
@lmuntaner what vendor is allowed to store identity FIDO2-compliant passkey?

**Comment by lmuntaner** [comment]
> @lmuntaner what vendor is allowed to store identity FIDO2-compliant passkey?

All the FIDO2-compliant should work with Internet Identity. Do you have problems with your device?
