### ISSUE TITLE
Dev II wasm broken in `release-2024-01-05`

### ISSUE THREAD

**Issue by Gekctek** [dfinity/internet-identity#2237]
I have been using version [release-2023-11-17](https://github.com/dfinity/internet-identity/releases/tag/release-2023-11-17) with the wasm hash `17620cf418fae5bf743db00256451c164794c4bd0ddd23668571c21bdc525884` using `dfx deps` with no issue

Today i did a dfx deps pull and it updated to the latest version [release-2024-01-05: Various Maintenance Changes](https://github.com/dfinity/internet-identity/releases/tag/release-2024-01-05) with wasm hash `d18a583e10574a1a06040d95322c160696701e1d8b32cc5738add752aaad0157` and i just get a blank screen

Looking at the console/network, it seems the `spa.js` file request is rejected with a `400 bad request`, so nothing on the page is loaded

I successfully reverted back to the previous version and it is working fine again.

I did the normal clearing cache and whatnot with the new version, but there was no change. Not sure whats going on

**Comment by frederikrothenberger** [comment]
Hi @Gekctek 

Are you using the query parameter based URL to access the II (i.e. `http://localhost:4943/?canisterId=<canisterId>`)?

If you are using Chrome or Firefox, you need to use subdomain based routing approach (`http://<canisterId>.localhost:4943/`) because the query parameter gets lost when loading multiple JS bundles transitively.

See also [this section](https://github.com/dfinity/internet-identity#local-replica) in the readme.

Please let me know if this does not resolve the issue.

**Comment by Gekctek** [comment]
It seemed like it was loading the canister, because if I removed the query parameter it would fail routing. And i would get the proper index html for the II page, but i would just fail to load any of the JS because of rejected (400) http request to get it

I was just using the JS agent's 'login' that opens a new page and that has been working fine in every browser for a while, until i updated the II canister for local development. Was there a breaking change that requires an updated version of the js agent?

**Comment by frederikrothenberger** [comment]
The breaking change was splitting II into multiple JS bundles.
But the solution is not to update the agent, but rather configure a different URL, [like so](https://github.com/dfinity/internet-identity/blob/2dc9c7fcea21c8b2d2a6d6b7d68f6bcdc6ae2404/demos/using-dev-build/webapp/index.ts#L55).

**Comment by Gekctek** [comment]
Thank you, that seemed to have worked
