### ISSUE TITLE
i`m doing .net maui app with webview for this website and i have an issue

### ISSUE THREAD

**Issue by eyadaymen** [dfinity/internet-identity#2417]
i`m doing .net maui app with webview for this website for this website https://dinewme.com/  and when I open login page with internet identity show me this error " browser not support "
![photo_2024-04-10_14-39-14](https://github.com/dfinity/internet-identity/assets/77113256/f21db248-823d-42b4-bb4a-ab5dc24a80c3)
and this is the source code in git repo
https://github.com/BoodyAna/Dinwme

can I know the reason and how I can fix it

**Comment by frederikrothenberger** [comment]
Hi @eyadaymen 

II requires a secure context to run in. You cannot run II in a WebView for that reason. The recommended way of doing authentication with II for native apps is to use a proxy website and open that in the system browser. You can refer to [this](https://github.com/dfinity/examples/tree/master/native-apps/unity_ii_applink) example for inspiration.
