### ISSUE TITLE
Not following the Passkey standard propely, breaking keepassxc passkeys

### ISSUE THREAD

**Issue by Tofixrs** [dfinity/internet-identity#2560]
Was trying to register to open chat, but it kept failing, looked into the console greeted with this message
```
TypeError: challenge is shorter than required minimum length.
    checkErrors moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys-utils.js:27
    buildCredentialCreationOptions moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys-utils.js:58
    enablePasskeys moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/keepassxc-browser.js:919
    postMessageToExtension moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys.js:88
    postMessageToExtension moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys.js:72
    create moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys.js:151
    Kg https://identity.ic0.app/spa.js:362
    create https://identity.ic0.app/spa.js:362
    r https://identity.ic0.app/spa.js:922
    t0 https://identity.ic0.app/spa.js:922
    r https://identity.ic0.app/spa.js:974
    nr https://identity.ic0.app/spa.js:361
    constructPasskey https://identity.ic0.app/spa.js:974
    s https://identity.ic0.app/spa.js:941
    handleEvent https://identity.ic0.app/spa.js:53
```

Thought it was a keepassxc bug but the developer told me that challange needs to be atleast 16 bytes in length as were ii uses only 9 
![image](https://github.com/user-attachments/assets/4745dfcc-885f-4b6c-900b-22b4e3222402)

Since on linux i dont have any other way of using passkeys (not that i am aware of) this blocks me out of websites using it

**Comment by frederikrothenberger** [comment]
Hi @Tofixrs 

Thanks for the report. How was it determined that Internet Identity is using only 9 bytes?
The code actually generates 16 bytes as necessary, see here: https://github.com/dfinity/internet-identity/blob/09c024c1fc7fe805387990bef8115f6afc3365d0/src/frontend/src/utils/iiConnection.ts#L782

Maybe if you could provide us with the reproduction steps, we could take a look ourselves?
Thanks!

**Comment by frederikrothenberger** [comment]
@Tofixrs: We will address the issue in #2561.

Thanks again for the report!
