### ISSUE TITLE
the server responded with a status of 400

### ISSUE THREAD

**Issue by PinappleUnderTheSea** [dfinity/internet-identity#2647]
Hi, I am a freshman of ICP. I met some problem when deploying internet-identity. Thanks for your help

I downloaded `.wasm.gz` and `.did` in my source dir, the write `dfx.json` like:
```
"internet_identity": {
      "type": "custom",
      "candid": "internet_identity/internet_identity.did",
      "wasm": "internet_identity/internet_identity_production.wasm.gz",
      "remote": {
        "id": {
          "ic": "rdmx6-jaaaa-aaaaa-aaadq-cai"
        }
      },
      "frontend": {}    
    }

```

After I ran `dfx deploy`,  the terminal returns:
```
    internet_identity:
      - http://127.0.0.1:4943/?canisterId=be2us-64aaa-aaaaa-qaabq-cai
      - http://be2us-64aaa-aaaaa-qaabq-cai.localhost:4943/
```

But when I input `http://127.0.0.1:4943/?canisterId=be2us-64aaa-aaaaa-qaabq-cai` or `http://127.0.0.1:4943/?canisterId=be2us-64aaa-aaaaa-qaabq-cai#authorize` , there is always an empty page.

The console shows that :
![image](https://github.com/user-attachments/assets/e08ce9fc-eb60-4352-90ac-f07ec5a21651)

Could you please tell me how to fix it?

**Comment by frederikrothenberger** [comment]
Hi @PinappleUnderTheSea

The problem might be related to routing. Please see [this](https://github.com/dfinity/internet-identity?tab=readme-ov-file#local-replica) section of the readme, in particular that paragraph:

> To access Internet Identity or configure it for your dapp, use one of the following URLs:
> *   Chrome, Firefox: http://<canister_id>.localhost:4943
> *   Safari: http://localhost:4943?canisterId=<canister_id>

**Comment by PinappleUnderTheSea** [comment]
Thanks so much! This problem is solved. But another problem happens:
![image](https://github.com/user-attachments/assets/5f13abba-68f6-406d-ba4a-54433b95860a)
seems like the pic could not be generaed.

Is it required to have internet connection?

**Comment by frederikrothenberger** [comment]
@PinappleUnderTheSea: Are there any errors in the browser console?
Which version of II are you deploying? Is it a dev or prod build?

**Comment by PinappleUnderTheSea** [comment]
I use proction version. The console shows after I verify my device:
![image](https://github.com/user-attachments/assets/56df54da-24ae-4b5f-9499-bcface452bcd)

**Comment by frederikrothenberger** [comment]
Ah, yes. This does not work. Please use either the dev (if you simply want to test the integration with your dapp) or test (if you want to have real Passkey interactions) version.

The reason prod does not work on the local replica is because all interactions with the network are verified. The prod version has the mainnet IC root key hard-coded and refuses to work against any other network (as this could be an attack). So you cannot use that unfortunately.

Any specific reason why you need the prod version?

**Comment by PinappleUnderTheSea** [comment]
I did not known the difference and randomly choose a version haha. It works after i switch to dev version. thx!!!!
