### ISSUE TITLE
Change UX for deleting last (FIDO) device + improve account security

### ISSUE THREAD

**Issue by p-** [dfinity/internet-identity#266]
Currently an internet-identity user can delete their last FIDO device without being fully aware what it really means: **the destruction of the account**.

### Demonstration
When deleting the last device two warnings are shown:

The default one:
![delete-last-device](https://user-images.githubusercontent.com/176818/118249128-97cebd00-b494-11eb-9724-acdbc833bed3.png)

A special one for the deletion of the last device:
![delete-last-device2](https://user-images.githubusercontent.com/176818/118249147-9d2c0780-b494-11eb-8ecc-6260ad0dd516.png)

With a soft message:

> This will remove your only remaining identity and may impact your ability to log in to accounts you have linked

The use of "may" seems to be kind of an understatement here :wink: 

### Suggestions
Instead of just changing the soft message displayed, the UX of removing the last device should be changed.
Following suggestions:

- Don't allow the deletion of the last device.
- Add a separate button to delete the account (which will of course remove the last device).
- When deleting the account (and thus the last device), the user should be prompted to verify the deletion with their device. -> This will make it harder to accidentally destroy the account (e.g. by a user using the same computer)

**Comment by nomeata** [comment]
Thanks! Absolutely correct analysis, and good suggestion! 
We are in the process to not just fix various UX issues, but also become more principled in how we approach UX, so we might not fix this right away. But thanks for reporting, and we'll get to it in due time

**Comment by nmattia** [comment]
We don't allow removing the last device anymore, so I'm gonna close this. Thanks for the suggestion!


<img width="456" alt="Screenshot 2022-04-11 at 11 54 57" src="https://user-images.githubusercontent.com/6930756/162714144-8e3f02cd-27e7-45b9-87aa-bdbfafdae8c4.png">

**Comment by neokree** [comment]
@nmattia Sorry to bother you, but now I would like to delete my account (just created a new one for testing purposes) and I can't. 

I think that it would be correct to allow user delete their accounts if they want, they just need to be sure they know the implications.

**Comment by nmattia** [comment]
hi @neokree,

We're updating the FAQ a bit, but from a technical point of view there is absolutely no difference between deleting an anchor and removing all devices. I'll have a look at how we could allow deleting the last device in a safe way. Thanks for bringing it up!
