### ISSUE TITLE
Security key

### ISSUE THREAD

**Issue by nicovogelaar** [dfinity/internet-identity#269]
I'm trying to register my laptop (Macbook). Is it possible to do this without owning a hardware security key or using my phone as a security key? I managed to register my phone (Android) through the Chrome browser with the lock-screen method. 

When I navigate to: https://identity.ic0.app, click "Already registered but using a new device?" and fill in my Identity number, the only option is to use a security key.

**Comment by nicovogelaar** [comment]
For local development, is there a way to use an identity in the browser after creating it with `dfx identity new ...`?

**Comment by nomeata** [comment]
Thanks for your interest! That’s two questions in one issue :-)

The first one is more a user question, right? These are probably better asked on the forum or via support (https://forum.dfinity.org/) to keep this here focused on development issues.

For the latter, may I point you to https://forum.dfinity.org/t/dfinity-auth-client-403-response/3618/8?u=nomeata?

**Comment by nicovogelaar** [comment]
Thank you @nomeata for pointing me to the appropriate channel!
