### ISSUE TITLE
CLEAN UP DEBUGGING LOG: Someone might have forgotted to remove a logging statement somewhere

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/internet-identity#2715]
<img width="400" alt="image" src="https://github.com/user-attachments/assets/bfdc1f58-245b-4314-8951-599da485dcfa">

Shows up on any app during authentication when you've clicked on your identity anchor and waiting for your device passkey process

**Comment by lmuntaner** [comment]
Thanks for the feedback! We also saw it and this will be fixed in the next release.
