### ISSUE TITLE
 Face ID  clearing the Cache

### ISSUE THREAD

**Issue by XuechengSong** [dfinity/internet-identity#281]
I have a serious issue. I have created an account on my iPhone using Face ID as a security key. I don’t use a physical token.
Now after clearing the Cache.  I try to log in but the Face ID verification is not possible anymore. The website ist just asking for a physical token.

i don't have other device

**Comment by XuechengSong** [comment]
I added the device in the Google browser on the same phone . However, I need to verify it in the previous Safari browser. The cache has been cleared, so I cannot verify it. As a result, I cannot restore my account, what should I do

**Comment by nomeata** [comment]
Sorry for these inconveniences. Would you submit a support request at https://support.dfinity.org/ for this? Closing this here, as this is not an issue with software in this repository (or the other where you cross-posted this).
