### ISSUE TITLE
Running locally: Fail to verify certificate

### ISSUE THREAD

**Issue by skilesare** [dfinity/internet-identity#291]
I got my ID canister running locally, but when I try to create a new Identity I get the following error.

![image](https://user-images.githubusercontent.com/643387/119196857-78173600-ba4c-11eb-8677-c509caf08a88.png)

A couple of messages from the console:

Fetch failed loading: POST "http://localhost:8000/api/v2/canister/rwlgt-iiaaa-aaaaa-aaaaa-cai/call".

index.js:2 Fetch finished loading: POST "http://localhost:8000/api/v2/canister/rwlgt-iiaaa-aaaaa-aaaaa-cai/read_state".

If I try to run the provided `dfx canister call internet_identity register '(123, "test", vec {1; 2; 3}, null)'`

I get:

```
The wallet canister on the "local" network for user "default" is "rrkah-fqaaa-aaaaa-aaaaq-cai"
Invalid data: Unable to serialize Candid values: type mismatch: 123 can not be of type record {
  alias : text;
  pubkey : DeviceKey;
  key_type : KeyType;
  purpose : Purpose;
  credential_id : opt CredentialId;
}
```

**Comment by skilesare** [comment]
I have tried to decode the body being sent and I see some strange stuff in it, including https://goo.gl/yabPex which links to some webauthn warning code from google.

**Comment by skilesare** [comment]
It looks like the request to the canister is actually succeeding, and state is coming back from the canister. I can't pinpoint where the thing is actually throwing.  Cbor + Typescript debugging is not super intuative. Is there an easy tool we can use to translate cbor responses/requests into standard data structures....or at least something more readable?

**Comment by skilesare** [comment]
Looks like the issue is this: https://forum.dfinity.org/t/fail-to-verify-certificate-in-development-update-calls/4078/6

**Comment by nomeata** [comment]
Yes, this is expected and a known limitation of how Canister Signatures work at the moment. We have plans for a more convenient work-around, but until then your only option is to deploy the Internet Identity locally during development. Also see https://github.com/dfinity/cancan/blob/main/docs/local-with-internet-identity.md for how the CanCan project handles this.
