### ISSUE TITLE
Check canister id in `post_upgrade`

### ISSUE THREAD

**Issue by nomeata** [dfinity/internet-identity#315]
Currently, we hard-code the canister id in the canister itself, at least in the frontend. (We could do it differently and let the canister inject the canister id into the front end code somehow). Since we have that information, it seems prudent to check, in `canister_init` and `canister_post_upgrade`, whether the actual canister id is as expected, and trap if it does not.

This would also be a good safeguard against accidentialy installing the Internet Identity canister over another NNS canister.

**Comment by nmattia** [comment]
I think the simplest solution would be to add `/canister_id` [here](https://github.com/dfinity/internet-identity/blob/da7ecaa85ef5003936368a43cf756c703dcb0899/src/frontend/src/utils/iiConnection.ts#L38) and replace `canisterId` with a singleton (not the haskell kind, [this](https://en.wikipedia.org/wiki/Singleton_pattern) kind) that fetches from `/canister_id`. WDYT?

**Comment by nomeata** [comment]
Not sure I follow. Are you describing how to not hardcode the canister id in the frontend?

**Comment by nmattia** [comment]
My bad, yes of course! Is there any other reason why we'd check the canister ID?

**Comment by nomeata** [comment]
The reason to check the canister id in post_upgrade is to fail at the last moment if an mistake in a canister upgrade proposal would otherwise override, say, the ledger.

But actually since @roman-kashitsyn 's stable memory format includes a magic string that is being checked, that should be sufficient, so I'll close this.
