### ISSUE TITLE
Write an integration guide for Internet Identity for developers.

### ISSUE THREAD

**Issue by Eve832** [dfinity/internet-identity#322]
Use blogs by Kyle and Joachim.
https://kyle-peacock.com/blog/dfinity/integrating-internet-identity/
https://forum.dfinity.org/t/verifying-the-code-of-the-internet-identity-service-a-walk-through/4650

**Comment by Eve832** [comment]
I am a developer that is interested in using Internet Identity.
How does it work?
How does it _really_ work?
Why should I use it?
How do I use it?
When is it not advisable to use?

**Comment by Eve832** [comment]
Link to Google WIP: https://docs.google.com/document/d/1Un2CJo6niIkoCN2RQKf2p1GWmc40mLXn3Ya1tYVM3Tk/edit

**Comment by phkla1** [comment]
> Link to Google WIP: https://docs.google.com/document/d/1Un2CJo6niIkoCN2RQKf2p1GWmc40mLXn3Ya1tYVM3Tk/edit

Hi. Yes we need this. Sent you a request for access to the doc.

**Comment by kritzcreek** [comment]
@phkla1 I'd recommend that you follow the mentioned blog post here: https://kyle-peacock.com/blog/dfinity/integrating-internet-identity/ which gives you the high-level view of how to integrate with your app.

If you need access to a lower level, or want to write your own auth client you can follow the documentation here: https://github.com/dfinity/internet-identity/blob/3a0cebe7fa60b71f3a7a7cc25127171bcee52ca4/docs/internet-identity-spec.adoc#client-auth-protocol

**Comment by phkla1** [comment]
> @phkla1 I'd recommend that you follow the mentioned blog post here: https://kyle-peacock.com/blog/dfinity/integrating-internet-identity/ which gives you the high-level view of how to integrate with your app.
> 
> If you need access to a lower level, or want to write your own auth client you can follow the documentation here: https://github.com/dfinity/internet-identity/blob/3a0cebe7fa60b71f3a7a7cc25127171bcee52ca4/docs/internet-identity-spec.adoc#client-auth-protocol

@kritzcreek thanks. I'm actually looking to help (another) newbie who might face some of the documentation issues that I did. The two docs you cited are great and I was (eventually) able to work through them, but I had to jump around many other docs in order to get a satisfactory (for me) understanding...e.g. what is @dfinity/agent? @dfinity/authentication? @dfinity/identity? how does Kyle's project structure align with the quickstart?..etc..etc.  I want to help fill that documentation gap.

**Comment by nmattia** [comment]
Added more information in the README and added a [demo project](https://github.com/dfinity/internet-identity/tree/main/demos/using-dev-build), hope this helps! Feel free to open another ticket for more specific issues.
