### ISSUE TITLE
Unable to recover account using first four letters of words in seed phrase

### ISSUE THREAD

**Issue by paulyoung** [dfinity/internet-identity#331]
The source code for Internet Identity suggests that the seed phrase is a BIP39 mnemonic.

Some backup solutions only allow storing the first 4 letters in accordance with the BIP39 protocol. My understanding is that the first-four-letter combinations are unique and sufficient to recover the full word.

However, when I try recovering an account using only the first four letters of each word in the seed phrase I get the "invalid seedphrase" message.

**Comment by nomeata** [comment]
Did you also shorten the ID number in the beginning? Not sure if the II frontend checks that number.

**Comment by paulyoung** [comment]
I tried both shortening that number and omitting the number.

**Comment by nomeata** [comment]
The README of https://www.npmjs.com/package/bip39 very prominently says

> **Please remember to allow recovery from mnemonic phrases that have invalid checksums (or that you don't have the wordlist)**
> 
> When a checksum is invalid, warn the user that the phrase is not something generated by your app, and ask if they would like to use it anyway. This way, your app only needs to hold the wordlists for your supported languages, but you can recover phrases made by other apps in other languages.
> 
> However, there should be other checks in place, such as checking to make sure the user is inputting 12 words or more separated by a space. ie. phrase.trim().split(/\s+/g).length >= 12

So I guess we should do that :-)

**Comment by paulyoung** [comment]
It seems like someone already did: https://github.com/dfinity/internet-identity/pull/289

**Comment by kritzcreek** [comment]
> Did you also shorten the ID number in the beginning? Not sure if the II frontend checks that number.

You'll have to omit the number probably. It's not part of the phrase and the frontend just strips it when reading the seedphrase.

> It seems like someone already did: #289

We're strictly checking that validation passes in the frontend. If we want to allow this "stripped" seed phrase to work, I think the best way of going about this would be to let the user continue even if we have validation failures here: https://github.com/dfinity/internet-identity/blob/17e5c867ab0c8d8500721e45ab8b87d7ae8e75ef/src/frontend/src/flows/recovery/inputSeedPhrase.ts#L53-L59

Something like a "Continue anyway" button.

That way we can still give the user an early indication that they might have pasted an incomplete seed phrase.

**Comment by paulyoung** [comment]
If I implement this do I get to submit the proposal to the NNS? 🙂

**Comment by nomeata** [comment]
Why not? :-)

**Comment by paulyoung** [comment]
I think a user experience improvement here could be to autocomplete words from the BIP39 word list (done entirely on the front end so that nothing is sent over the wire)

**Comment by nmattia** [comment]
Yes, completely agree. We do have a ticket to track this internally, just need to find the time!
