### ISSUE TITLE
Call with register function failed

### ISSUE THREAD

**Issue by feliciss** [dfinity/internet-identity#347]
After deploying, call `dfx canister call internet_identity register '(123, "test", vec {1; 2; 3}, null)'`

Got: 

```
Invalid data: Unable to serialize Candid values: type mismatch: 123 can not be of type record {
  alias : text;
  pubkey : DeviceKey;
  key_type : KeyType;
  purpose : Purpose;
  credential_id : opt CredentialId;
}
```

**Comment by kritzcreek** [comment]
The canister interface is defined here: https://github.com/dfinity/internet-identity/blob/main/src/internet_identity/internet_identity.did

`register` expects a single record as it's argument, but you're passing it a tuple of multiple ones here.

A good place to start might be to check out the documentation for [Candid's textual format](https://sdk.dfinity.org/docs/candid-guide/candid-concepts.html#textual-values)
