### ISSUE TITLE
Local docker build fails

### ISSUE THREAD

**Issue by jorgenbuilder** [dfinity/internet-identity#350]
```
 > [10/18] RUN cargo install ic-cdk-optimizer --version 0.3.0:
#13 0.227 /lib64/ld-linux-x86-64.so.2: No such file or directory
 ```

**Comment by nmattia** [comment]
This is an odd error, since the Ubuntu image should have the dynamic linker at `/lib64/ld-linux-x86-64.so.2`. If you get a chance, can you add a line in the `Dockerfile` that `stat`s that file?

``` Dockerfile
...
RUN stat /lib64/ld-linux-x86-64.so.2
...
```

**Comment by christyjacob4** [comment]
<img width="760" alt="Screenshot 2021-12-10 at 5 35 13 AM" src="https://user-images.githubusercontent.com/20852629/145502391-2ec4d40e-f1a7-419f-9e3e-c6e4f12fe388.png">


@nmattia  I did try this and the file could not be found.

**Comment by nmattia** [comment]
I've created a PR to pin the docker image: https://github.com/dfinity/internet-identity/pull/490

Would you mind running the following? It downloads the same image that we now pin and checks for the dynamic loader:

``` bash
docker run --rm ubuntu@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322 stat /lib64/ld-linux-x86-64.so.2
  File: /lib64/ld-linux-x86-64.so.2 -> /lib/x86_64-linux-gnu/ld-2.31.so
  Size: 32              Blocks: 0          IO Block: 4096   symbolic link
Device: 4ah/74d Inode: 4305477956  Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-12-16 11:04:55.000000000 +0000
Modify: 2020-12-16 11:04:55.000000000 +0000
Change: 2021-12-14 09:50:06.470212214 +0000
 Birth: -
```

**Comment by nmattia** [comment]
Assuming this is fixed! Please re-open if you run into the issue again.
