### ISSUE TITLE
dfx deploy fails

### ISSUE THREAD

**Issue by phkla1** [dfinity/internet-identity#367]
dfx 0.8.0, rust 1.51, node 12.18, MacOS Catalina

After npm install, **II_ENV=development dfx deploy --no-wallet --argument '(null)'**  fails with errors:

error[E0463]: can't find crate for `core` |= note: the `wasm32-unknown-unknown` target may not be installed
error: aborting due to previous error
For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if`

rustc --explain E0463  --> **A plugin/crate was declared but cannot be found**.

**Comment by kritzcreek** [comment]
You're going to need to run `rustup target add wasm32-unknown-unknown`
