### ISSUE TITLE
Fix UI for new Merge Maturity button

### ISSUE THREAD

**Issue by lopezi** [dfinity/internet-identity#380]
As a mobile user I would like to have a better UI for the newly added Merge Maturity button and respective merge maturity percentage.

![maturity](https://user-images.githubusercontent.com/388476/132338797-74ecf84b-f780-438c-8adb-7417e7928dc8.png)

**Comment by nomeata** [comment]
This is a problem with the NNS UI, not the Internet Identity. Maybe try support.dfinity.org.

**Comment by nmattia** [comment]
Hi @lopezi ! As @nomeata, this is the wrong repo. Here is the repo you're looking for: https://github.com/dfinity/nns-dapp
