### ISSUE TITLE
No matching version found for kjua@^0.9.0.

### ISSUE THREAD

**Issue by lazy1523** [dfinity/internet-identity#387]
No matching version found for kjua@^0.9.0.

node version -v14.17.5
os:MacOs big sur

**Comment by lazy1523** [comment]
npm view kjua

kjua@0.6.0 | MIT | deps: none | versions: 10
https://larsjung.de/kjua/

dist
.tarball: https://registry.nlark.com/kjua/download/kjua-0.6.0.tgz
.shasum: dac355272b6e1baafd491eba780fcf4746cd8aaa

maintainers:
- lrsjng <lrsjng@gmail.com>

dist-tags:
latest: 0.6.0  

published over a year ago by lrsjng <lrsjng@gmail.com>
panhy@localhost ~/D/d/D/internet-identity (main)>

**Comment by lazy1523** [comment]
updaing "kjua": "^0.9.0" to "kjua": "^0.6.0",sussecc

**Comment by kritzcreek** [comment]
Sorry, can't reproduce:

```
C:\Users\creek> npm view kjua

kjua@0.9.0 | MIT | deps: none | versions: 12
Dynamically generated QR codes for modern browsers.
https://larsjung.de/kjua/

dist
.tarball: https://registry.npmjs.org/kjua/-/kjua-0.9.0.tgz
.shasum: 88603607318d67c231e9a5770c4bed4639e03310
.integrity: sha512-Wmh5k6hpl+wiYkcEIx0/Ocj1DOxacw/myh/SQ3NbY0RWD4360CXaaAJkdeeV+moqf7fxvACYK95LXQ8vtLWKxA==
.unpackedSize: 65.3 kB

maintainers:
- lrsjng <lrsjng@gmail.com>

dist-tags:
latest: 0.9.0
```

**Comment by lazy1523** [comment]
I have dealt with him ，Please switch to npmjs mirror
