### ISSUE TITLE
Creating a new device on Brave browser on mobile returns error

### ISSUE THREAD

**Issue by AdamPetroff** [dfinity/internet-identity#410]
Mobile version with chrome works fine, but when I try to add a device with Brave browser, it says authentication failed.
![Screenshot_20210922-110028](https://user-images.githubusercontent.com/17226878/134314959-f6c6dd84-1040-4e52-b36f-9b4b925d4931.png)

I tried disabling the brave shields, and checked my settings - I tried to turn off fingerprinting limitations, didn't help.

**Comment by kritzcreek** [comment]
Unfortunately Brave on Android does not support WebAuthn at this point in time. See also https://github.com/brave/brave-browser/issues/7756
