### ISSUE TITLE
WIndows 10: Confirm new device fails locally.

### ISSUE THREAD

**Issue by shawnrmoss** [dfinity/internet-identity#422]
Repo steps
1. Start II in a terminal - II_ENV=development dfx deploy --no-wallet --argument '(null)' 
2. Open in browser http://localhost:8000/?canisterId=rwlgt-iiaaa-aaaaa-aaaaa-cai#authorize
3. Create an Internet Identity Anchor
4. Fill in Device name and click create.
5. I get a pop up window to setup my security key and click ok.  Enter my pin. And touch my security key.
6. Confirm new device and am again prompted to touch my security key.
7.  Server returned an error:
     Code: 404 (Not Found)
     Body: Requested canister does not exist

Im stuck here.  Not being able to create any Identity Anchors locally.  

Any help would be greatly appreciated.]

**Comment by nmattia** [comment]
We have a new guide for running II locally: https://github.com/dfinity/internet-identity/tree/main/demos/using-dev-build#readme

I'm going to close this for now, feel free to re-open if you run into the issue again!
