### ISSUE TITLE
Need a full tutorial or 'clear' instructions on how to setup a local project to use Internet Identity running locally 

### ISSUE THREAD

**Issue by ferMartz** [dfinity/internet-identity#443]
Instructions on the README are very vague.

After a few hurdles I was able to run internet identity locally but there is no clear instruction on how to use it in a local development project.

**Comment by nmattia** [comment]
Yes, that makes sense. I'm adding this to my TODO list, hoping to get to this soon.

**Comment by nmattia** [comment]
Done! https://github.com/dfinity/internet-identity/tree/main/demos/using-dev-build
