### ISSUE TITLE
why is the publicKeyCredentialCreationOptions challenge not random

### ISSUE THREAD

**Issue by plitzenberger** [dfinity/internet-identity#491]
From [webauthn.guide](https://webauthn.guide/#registration):

> challenge: The challenge is a buffer of cryptographically random bytes generated on the server, and is needed to prevent "replay attacks".

From the [specs](https://w3c.github.io/webauthn/#sctn-cryptographic-challenges):

> As a cryptographic protocol, Web Authentication is dependent upon randomized challenges to avoid replay attacks. Therefore, the values of both PublicKeyCredentialCreationOptions.challenge and PublicKeyCredentialRequestOptions.challenge MUST be randomly generated by Relying Parties in an environment they trust (e.g., on the server-side), and the returned challenge value in the client’s response MUST match what was generated. This SHOULD be done in a fashion that does not rely upon a client’s behavior, e.g., the Relying Party SHOULD store the challenge temporarily until the operation is complete. Tolerating a mismatch will compromise the security of the protocol. 
> In order to prevent replay attacks, the challenges MUST contain enough entropy to make guessing them infeasible. Challenges SHOULD therefore be at least 16 bytes long.

But the implementation is not random:

[`createOptions`](https://github.com/dfinity/internet-identity/blob/86e867acce5a0c0e4b35a8dcf9269a8014283c7f/src/frontend/src/utils/iiConnection.ts#L389) used in [`register`](https://github.com/dfinity/internet-identity/blob/86e867acce5a0c0e4b35a8dcf9269a8014283c7f/src/frontend/src/flows/register.ts#L62)

**Comment by nmattia** [comment]
Hi there, thanks for bringing this up! My WebAuthn knowledge isn't great so I'll need to make myself smarter first. Hopefully I can come back with answers; in the meantime maybe @kritzcreek can shed some light.
