### ISSUE TITLE
Not getting front-end error when device count limit is reached

### ISSUE THREAD

**Issue by neeboo** [dfinity/internet-identity#588]
Error in console:

```javascript
Uncaught (in promise) Error: Call was rejected:
  Request ID: ...
  Reject code: 5
  Reject text: Canister rdmx6-jaaaa-aaaaa-aaadq-cai trapped explicitly: at most 10 authentication information entries are allowed per user
```
Expected to show a proper UI to frontend, and before adding device not after the process

**Comment by nmattia** [comment]
Ah, that's not expected indeed! Thanks, will have a look

**Comment by neeboo** [comment]
> @neeboo we just deployed the fix, can you confirm that it works for you?

Confirmed it worked!
