### ISSUE TITLE
Internet Identity Canister Id at ICP Mainnet

### ISSUE THREAD

**Issue by 7flash** [dfinity/internet-identity#662]
Where can I find it..

**Comment by nmattia** [comment]
This is the canister ID: "rdmx6-jaaaa-aaaaa-aaadq-cai" which you can find [here](https://github.com/dfinity/internet-identity/blob/b7fa2e617936b409c4bb1e570c539b455f9a9870/canister_ids.json#L3). 

But you shouldn't need it to interact with II, can you share some details about your use case?

**Comment by 7flash** [comment]
Thx got it.. also found in my env.. not interacting directly.. just had to emplace in there..

https://github.com/dfinity/internet-identity/blob/352058e45904c102e90c489ba05b86f84a364ea7/demos/using-dev-build/webapp/index.js#L24
