### ISSUE TITLE
Cannot run using-dev-build demo as a standalone project

### ISSUE THREAD

**Issue by massimoalbarello** [dfinity/internet-identity#725]
I tried running the demo as standalone:

1. I copied the folder [using-dev-build](https://github.com/dfinity/internet-identity/blob/main/demos/using-dev-build) in a separate directory.
2. I run the commands in the [README.md](https://github.com/dfinity/internet-identity/blob/main/demos/using-dev-build/README.md).
3. I got this error after the command `dfx deploy --no-wallet --argument '(null)'`:
  ```
  Error: Failed while trying to deploy canisters.
  Caused by: Failed while trying to deploy canisters.
    Failed to build call canisters.
      Failed while trying to build all canisters.
        The post-build step failed for canister 'rwlgt-iiaaa-aaaaa-aaaaa-cai' (internet_identity) with an embedded error: No such file or directory (os error 2) 
  ```

I found out that the problem was due to the symbolic link of `internet_identity.did` which is pointing to a file that doesn't exist anymore (as I'm using the using-dev-build as standalone). To fix this I substituted it with a copy of the [file](https://github.com/dfinity/internet-identity/blob/main/src/internet_identity/internet_identity.did) pointed by the symbolic link.

I suggest adding instruction to copy the file `internet_identity.did` to the README.md so that you can actually run the demo as standalone.

**Comment by Luca8991** [comment]
I also got this error and now, using this fix, it works! Thanks @massimoalbarello

**Comment by nmattia** [comment]
Thanks for the report! I was out for some time but I'll give it a try today

**Comment by Acetarax** [comment]
> I tried running the demo as standalone:
> 
> 1. I copied the folder [using-dev-build](https://github.com/dfinity/internet-identity/blob/main/demos/using-dev-build) in a separate directory.
> 2. I run the commands in the [README.md](https://github.com/dfinity/internet-identity/blob/main/demos/using-dev-build/README.md).
> 3. I got this error after the command `dfx deploy --no-wallet --argument '(null)'`:
> 
> ```
> Error: Failed while trying to deploy canisters.
> Caused by: Failed while trying to deploy canisters.
>     Failed to build call canisters.
>       Failed while trying to build all canisters.
>         The post-build step failed for canister 'rwlgt-iiaaa-aaaaa-aaaaa-cai' (internet_identity) with an embedded error: No such file or directory (os error 2) 
> ```
> 
> I found out that the problem was due to the symbolic link of `internet_identity.did` which is pointing to a file that doesn't exist anymore (as I'm using the using-dev-build as standalone). To fix this I substituted it with a copy of the [file](https://github.com/dfinity/internet-identity/blob/main/src/internet_identity/internet_identity.did) pointed by the symbolic link.
> 
> I suggest adding instruction to copy the file `internet_identity.did` to the README.md so that you can actually run the demo as standalone.

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by Luca8991** [comment]
@Acetarax can you explain better how your hint applies to this issue?

**Comment by nmattia** [comment]
@massimoalbarello pushed a fix! can you see if it works for you?
