### ISSUE TITLE
using II for local development in Safari fails

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/internet-identity#776]
# Motivation

As a developer I want to be able to develop my dapp locally with II installed locally as well. This works well with Chrome or Firefox but unfortunately, fails in Safari.

e.g. given II local path `http://127.0.0.1:8000/?canisterId=rwlgt-iiaaa-aaaaa-aaaaa-cai` I get an error "Fail to load resource through https"

# Reproduction

```
npm init ic
follow the prompt, create a project with II, start dfx and deploy
open the provided II link in Safari
```

# Screenshots

Safari:

<img width="1498" alt="Capture d’écran 2022-07-29 à 09 47 41" src="https://user-images.githubusercontent.com/16886711/181722317-794c20ea-759c-42ab-a9d8-c96fb3f2e397.png">

Chrome for comparison:

<img width="1510" alt="Capture d’écran 2022-07-29 à 09 47 52" src="https://user-images.githubusercontent.com/16886711/181722347-0d5cc09c-3c1d-41d3-96b1-a474ba9d4f1a.png">

**Comment by nmattia** [comment]
Thanks for the report, I can reproduce this. Will get on it asap.

**Comment by nmattia** [comment]
Actually gave this a thought; while `npm run start` will now work with Safari (because we're using webpack to serve the HTML) I fear the problem may persist when using the canister independently (since there CSP headers still comme straight from the canister). Thoughts?

**Comment by nmattia** [comment]
Yeah, can still reproduce this. I think the best way forward is to add a new build feature to [disable CSP](https://github.com/dfinity/internet-identity#features) and have the dev version use that. @peterpeterparker or @frederikrothenberger wanna give this a try?
