### ISSUE TITLE
CSS reset

### ISSUE THREAD

**Issue by wackyleo459** [dfinity/internet-identity#785]
Due to possible inconsistent styling across different browsers, suggestion is to have css reset styling. For our purposes, having a custom separate css reset stylesheet with needed normalized styling (such as lists) should do the trick.

Guidelines:
- https://www.webfx.com/blog/web-design/css-tip-1-resetting-your-styles-with-css-reset/
- https://meyerweb.com/eric/tools/css/reset/index.html

Possible tool/option:
https://necolas.github.io/normalize.css/

**Comment by meodai** [comment]
I think we agreed on using a reset not a normalize. I usually just use that one https://github.com/elad2412/the-new-css-reset

**Comment by wackyleo459** [comment]
https://github.com/dfinity/internet-identity/pull/796
