### ISSUE TITLE
background and contrast issue on iOS

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/internet-identity#861]
# Issue

On iOS the new background is not present and the contrast is hard to read. Tested on iPhone 13 mini.

As discussed @meodai 

# Screenshot

![Capture d’écran   2022-09-01 à 18 22 47](https://user-images.githubusercontent.com/16886711/187969333-18783cb0-0b44-4f98-a18b-126d5b4c7f18.png)

**Comment by meodai** [comment]
https://github.com/dfinity/internet-identity/pull/862
