### ISSUE TITLE
Warnbox border gradient is cut off on iPad

### ISSUE THREAD

**Issue by nmattia** [dfinity/internet-identity#931]
On Safari iPadOS I get the following, where the warnbox gradient seems to be cut off abruptly at the bottom:

![IMG_0687](https://user-images.githubusercontent.com/6930756/193253413-935febef-682f-46e8-83d9-7d385bb03580.PNG)

**Comment by nmattia** [comment]
iPad Pro, 2019

**Comment by nmattia** [comment]
Ah @meodai , only happens in landscape mode it seems

**Comment by meodai** [comment]
@nmattia can you specify the IOS version please? Apparently I can not test anything lower than 16 in the simulator. (my personal ipad is also up to date unfortunately)

**Comment by meodai** [comment]
![Screenshot 2022-10-03 at 17 15 39](https://user-images.githubusercontent.com/608386/193613870-d946d257-f6a6-4b63-abc8-fcbb1862e0ac.png)

**Comment by meodai** [comment]
PS: do you also have this issue on localhost? in the showcase

**Comment by meodai** [comment]
![Screenshot 2022-10-03 at 17 19 48](https://user-images.githubusercontent.com/608386/193614492-01b685e5-b334-47d9-a6af-7149efe59d75.png)

**Comment by nmattia** [comment]
iPadOS 15.7; cannot reproduce with the showcase! I don't know what the issue is but it seems this is very specific, let's just forget about it for now!

**Comment by meodai** [comment]
OK lets do that :D
